// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const images = {
  "portal-cafe/hero": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/hero-480.webp",
        480
      ],
      [
        "/work/portal-cafe/hero-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/carta": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/carta-480.webp",
        480
      ],
      [
        "/work/portal-cafe/carta-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/experiencia": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/experiencia-480.webp",
        480
      ],
      [
        "/work/portal-cafe/experiencia-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/momentos": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/momentos-480.webp",
        480
      ],
      [
        "/work/portal-cafe/momentos-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/galeria": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/galeria-480.webp",
        480
      ],
      [
        "/work/portal-cafe/galeria-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/visitanos": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/visitanos-480.webp",
        480
      ],
      [
        "/work/portal-cafe/visitanos-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/panel-qr": {
    "width": 788,
    "height": 492,
    "srcset": [
      [
        "/work/portal-cafe/panel-qr-480.webp",
        480
      ],
      [
        "/work/portal-cafe/panel-qr-788.webp",
        788
      ]
    ]
  },
  "portal-cafe/mobile-hero": {
    "width": 469,
    "height": 1015,
    "srcset": [
      [
        "/work/portal-cafe/mobile-hero-240.webp",
        240
      ],
      [
        "/work/portal-cafe/mobile-hero-469.webp",
        469
      ]
    ]
  },
  "portal-cafe/mobile-carta": {
    "width": 469,
    "height": 1015,
    "srcset": [
      [
        "/work/portal-cafe/mobile-carta-240.webp",
        240
      ],
      [
        "/work/portal-cafe/mobile-carta-469.webp",
        469
      ]
    ]
  },
  "portal-cafe/mobile-momentos": {
    "width": 469,
    "height": 1015,
    "srcset": [
      [
        "/work/portal-cafe/mobile-momentos-240.webp",
        240
      ],
      [
        "/work/portal-cafe/mobile-momentos-469.webp",
        469
      ]
    ]
  }
} as const satisfies Record<string, ImageAsset>

export interface ImageAsset {
  width: number
  height: number
  srcset: ReadonlyArray<readonly [string, number]>
}

export type ImageKey = keyof typeof images
