/**
 * _source/ → public/work/<project>/<name>-<width>.webp + src/content/images.generated.ts
 * Requires ffmpeg/ffprobe on PATH. Run with `npm run images` after adding or replacing a capture.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** crop: [width, height] taken from the top-left corner, used to drop the browser scrollbar. */
const DESKTOP_CROP = [788, 492]

const MANIFEST = [
  ...['hero', 'carta', 'experiencia', 'momentos', 'galeria', 'visitanos', 'panel-qr'].map((name) => ({
    project: 'portal-cafe',
    name,
    crop: DESKTOP_CROP,
    widths: [480, 788],
  })),
  ...['mobile-hero', 'mobile-carta', 'mobile-momentos'].map((name) => ({
    project: 'portal-cafe',
    name,
    widths: [240, 469],
  })),
]

function probe(file) {
  const out = execFileSync('ffprobe', ['-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=width,height', '-of', 'csv=p=0', file])
  const [width, height] = out.toString().trim().split(',').map(Number)
  return { width, height }
}

const registry = {}

for (const entry of MANIFEST) {
  const input = join(root, '_source', entry.project, `${entry.name}.jpg`)
  const outDir = join(root, 'public', 'work', entry.project)
  mkdirSync(outDir, { recursive: true })

  const source = probe(input)
  const [baseW, baseH] = entry.crop ?? [source.width, source.height]
  const crop = entry.crop ? `crop=${baseW}:${baseH}:0:0,` : ''

  for (const width of entry.widths) {
    const output = join(outDir, `${entry.name}-${width}.webp`)
    execFileSync('ffmpeg', ['-y', '-v', 'error', '-i', input, '-vf', `${crop}scale=${width}:-2:flags=lanczos`, '-quality', '82', output])
  }

  registry[`${entry.project}/${entry.name}`] = {
    width: baseW,
    height: baseH,
    srcset: entry.widths.map((w) => [`/work/${entry.project}/${entry.name}-${w}.webp`, w]),
  }
  console.log('✓', entry.project, entry.name)
}

const source = `// Generated by scripts/optimize-images.mjs — do not edit by hand.
export const images = ${JSON.stringify(registry, null, 2)} as const satisfies Record<string, ImageAsset>

export interface ImageAsset {
  width: number
  height: number
  srcset: ReadonlyArray<readonly [string, number]>
}

export type ImageKey = keyof typeof images
`
writeFileSync(join(root, 'src', 'content', 'images.generated.ts'), source)
